spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fuwaiHos?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: root123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

